[options]
admin_passwd = $pbkdf2-sha512$600000$5Nw7h5Bybs1ZC.G8936vdQ$5lC5BrmIOPY0BkHCAKvgPtLdRQmKkaYS7Sv2qn1z.1J8jR6Ql3qVVFh9BGTsP.b53yFjV9c9oKwimX7RxYLTgg
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo.log
log_level = info
xmlrpc_port = 8069
longpolling_port = 8072
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 1073741824
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120

