#!/usr/bin/env python3
"""
Facebook/Instagram Poster

Publishes posts to Facebook Pages and Instagram Business accounts.
Supports approval workflow via Obsidian vault folders.
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from dotenv import load_dotenv

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))
from facebook_client import FacebookClient

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
)
logger = logging.getLogger(__name__)


class FacebookPoster:
    """Poster for Facebook and Instagram."""
    
    def __init__(self, vault_path: str):
        """
        Initialize Facebook Poster.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        load_dotenv()
        
        self.vault_path = Path(vault_path).resolve()
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.done = self.vault_path / 'Done'
        
        # Ensure folders exist
        for folder in [self.pending_approval, self.approved, self.done]:
            folder.mkdir(parents=True, exist_ok=True)
        
        # Initialize client
        self.client = FacebookClient()
    
    def _get_page_token(self) -> str:
        """Get page access token for posting."""
        import requests
        from dotenv import load_dotenv
        
        load_dotenv()
        
        user_token = os.getenv('META_ACCESS_TOKEN', '')
        page_id = os.getenv('META_PAGE_ID', '')
        
        # Get page access token
        r = requests.get(
            f'https://graph.facebook.com/v19.0/{page_id}',
            params={'fields': 'access_token', 'access_token': user_token}
        )
        result = r.json()
        
        if 'access_token' in result:
            return result['access_token']
        return user_token  # Fallback to user token
    
    def create_post_request(
        self,
        message: str,
        platform: str = 'facebook',
        image_url: Optional[str] = None,
        link: Optional[str] = None,
        scheduled_time: Optional[str] = None,
    ) -> Path:
        """
        Create a post request file in Pending_Approval folder.
        
        Args:
            message: Post content
            platform: 'facebook', 'instagram', or 'both'
            image_url: URL to image to post
            link: Link to share
            scheduled_time: Optional scheduled time
            
        Returns:
            Path to created file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'POST_{platform.upper()}_{timestamp}.md'
        filepath = self.pending_approval / filename
        
        content = f'''---
type: social_post_request
platform: {platform}
created: {datetime.now().isoformat()}
status: pending_approval
requires_approval: true
---

# Social Media Post Request

## Platform(s)
- **Target**: {platform.upper()}
- **Scheduled**: {scheduled_time or 'Immediate'}

## Content
{message}

{f'**Image**: {image_url}' if image_url else ''}
{f'**Link**: {link}' if link else ''}

## To Approve
1. Review the content above
2. Move this file to `/Approved` folder to publish
3. Move to `/Rejected` to cancel

## To Execute (after approval)
```bash
python scripts/facebook_poster.py --vault {self.vault_path} --execute --file "{filepath.name}"
```

---
*Generated by Facebook Poster | AI Employee v0.3 (Gold Tier)*
'''
        
        filepath.write_text(content, encoding='utf-8')
        logger.info(f'Created post request: {filepath.name}')
        
        return filepath
    
    def execute_post(self, filepath: Path) -> Dict[str, Any]:
        """
        Execute an approved post.
        
        Args:
            filepath: Path to approved post file
            
        Returns:
            Result dictionary
        """
        # Read the approved file
        content = filepath.read_text(encoding='utf-8')
        
        # Parse frontmatter and content
        try:
            # Split frontmatter and body
            if content.startswith('---'):
                parts = content.split('---', 2)
                frontmatter = parts[1].strip()
                body = parts[2].strip() if len(parts) > 2 else ''
                
                # Parse YAML-like frontmatter
                metadata = {}
                for line in frontmatter.split('\n'):
                    if ':' in line:
                        key, value = line.split(':', 1)
                        metadata[key.strip()] = value.strip()
            else:
                metadata = {}
                body = content
            
            # Extract post details from body
            platform = metadata.get('platform', 'facebook')
            
            # Find content section
            lines = body.split('\n')
            message_lines = []
            image_url = None
            link = None
            in_content = False
            
            for line in lines:
                if line.startswith('## Content'):
                    in_content = True
                    continue
                elif line.startswith('##'):
                    in_content = False
                elif in_content:
                    if line.startswith('**Image**'):
                        image_url = line.split(': ')[1] if ': ' in line else None
                    elif line.startswith('**Link**'):
                        link = line.split(': ')[1] if ': ' in line else None
                    elif line.strip() and not line.startswith('-'):
                        message_lines.append(line)
            
            message = '\n'.join(message_lines).strip()
            
        except Exception as e:
            logger.error(f'Failed to parse post file: {e}')
            return {'success': False, 'error': str(e)}
        
        if not message:
            return {'success': False, 'error': 'No message content found'}

        # Post to platforms
        results = {'facebook': None, 'instagram': None}

        try:
            if platform in ['facebook', 'both']:
                # Get page access token for posting
                page_token = self._get_page_token()
                
                # Use requests directly with page token
                import requests
                from dotenv import load_dotenv
                load_dotenv()
                page_id = os.getenv('META_PAGE_ID', '')
                
                r = requests.post(
                    f'https://graph.facebook.com/v19.0/{page_id}/feed',
                    data={
                        'message': message,
                        'access_token': page_token
                    }
                )
                post_result = r.json()
                
                if 'id' in post_result:
                    results['facebook'] = {
                        'success': True,
                        'post_id': post_result['id'],
                        'permalink': f'https://facebook.com/{post_result["id"]}'
                    }
                    logger.info(f'Facebook post created: {post_result["id"]}')
                else:
                    raise Exception(f'Facebook API error: {post_result.get("error", {}).get("message", "Unknown error")}')

            if platform in ['instagram', 'both']:
                if image_url:
                    results['instagram'] = self.client.create_instagram_post(
                        image_url=image_url,
                        caption=message,
                    )
                    logger.info(f'Instagram post created: {results["instagram"].get("media_id")}')
                else:
                    logger.warning('Instagram requires an image, skipping')

        except Exception as e:
            logger.error(f'Failed to post: {e}')
            return {'success': False, 'error': str(e)}
        
        # Create completion record
        self._create_done_record(filepath, results)
        
        # Move file to Done
        done_path = self.done / filepath.name
        filepath.rename(done_path)
        
        return {
            'success': True,
            'results': results,
            'done_file': str(done_path),
        }
    
    def _create_done_record(self, original_path: Path, results: Dict[str, Any]):
        """Create a record in Done folder."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'POST_COMPLETED_{timestamp}.md'
        filepath = self.done / filename
        
        # Read original content
        original_content = original_path.read_text(encoding='utf-8')
        
        content = f'''---
type: social_post_completed
completed: {datetime.now().isoformat()}
original_file: {original_path.name}
---

# Social Media Post - Completed

## Original Request
{original_content}

## Results

### Facebook
```json
{json.dumps(results.get('facebook', {}), indent=2)}
```

### Instagram
```json
{json.dumps(results.get('instagram', {}), indent=2)}
```

## Posted At
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---
*Generated by Facebook Poster | AI Employee v0.3 (Gold Tier)*
'''
        
        filepath.write_text(content, encoding='utf-8')
    
    def post_direct(
        self,
        message: str,
        platform: str = 'facebook',
        image_url: Optional[str] = None,
        link: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Post directly without approval workflow.
        
        Args:
            message: Post content
            platform: 'facebook', 'instagram', or 'both'
            image_url: URL to image
            link: Link to share
            
        Returns:
            Result dictionary
        """
        results = {'facebook': None, 'instagram': None}
        
        try:
            if platform in ['facebook', 'both']:
                if image_url:
                    results['facebook'] = self.client.create_photo_post(
                        photo_url=image_url,
                        caption=message,
                    )
                else:
                    results['facebook'] = self.client.create_page_post(
                        message=message,
                        link=link,
                    )
            
            if platform in ['instagram', 'both']:
                if image_url:
                    results['instagram'] = self.client.create_instagram_post(
                        image_url=image_url,
                        caption=message,
                    )
                else:
                    logger.warning('Instagram requires an image')
            
        except Exception as e:
            logger.error(f'Failed to post: {e}')
            return {'success': False, 'error': str(e)}
        
        return {
            'success': True,
            'results': results,
        }


def parse_args():
    parser = argparse.ArgumentParser(description='Facebook/Instagram Poster')
    parser.add_argument('--vault', required=True, help='Path to Obsidian vault')
    parser.add_argument('--message', help='Post message content')
    parser.add_argument('--platform', choices=['facebook', 'instagram', 'both'], default='facebook')
    parser.add_argument('--image-url', help='URL to image')
    parser.add_argument('--link', help='Link to share')
    parser.add_argument('--request', action='store_true', help='Create approval request')
    parser.add_argument('--execute', action='store_true', help='Execute approved post')
    parser.add_argument('--file', help='Path to approved post file')
    parser.add_argument('--direct', action='store_true', help='Post directly (no approval)')
    return parser.parse_args()


def main():
    args = parse_args()
    
    poster = FacebookPoster(vault_path=args.vault)
    
    # Execute approved post
    if args.execute and args.file:
        filepath = Path(args.file)
        if not filepath.is_absolute():
            # Look in Approved folder
            filepath = poster.approved / args.file
        
        if filepath.exists():
            result = poster.execute_post(filepath)
            print(json.dumps(result, indent=2))
            return 0 if result.get('success') else 1
        else:
            print(f'File not found: {filepath}')
            return 1
    
    # Create approval request
    if args.request and args.message:
        filepath = poster.create_post_request(
            message=args.message,
            platform=args.platform,
            image_url=args.image_url,
            link=args.link,
        )
        print(f'Created approval request: {filepath}')
        return 0
    
    # Direct post (no approval)
    if args.direct and args.message:
        result = poster.post_direct(
            message=args.message,
            platform=args.platform,
            image_url=args.image_url,
            link=args.link,
        )
        print(json.dumps(result, indent=2))
        return 0 if result.get('success') else 1
    
    # Default: show usage
    print('Facebook/Instagram Poster')
    print('=' * 50)
    print('\nUsage:')
    print('1. Create approval request:')
    print('   python facebook_poster.py --vault PATH --request --message "Hello!"')
    print('\n2. Execute approved post:')
    print('   python facebook_poster.py --vault PATH --execute --file POST_FACEBOOK_*.md')
    print('\n3. Direct post (no approval):')
    print('   python facebook_poster.py --vault PATH --direct --message "Hello!"')
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
