#!/usr/bin/env python3
"""
Twitter Poster

Publishes tweets and threads to Twitter/X.
Supports approval workflow via Obsidian vault folders.
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))
from twitter_client import TwitterClient

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
)
logger = logging.getLogger(__name__)


class TwitterPoster:
    """Poster for Twitter/X."""
    
    def __init__(self, vault_path: str):
        """
        Initialize Twitter Poster.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        load_dotenv()
        
        self.vault_path = Path(vault_path).resolve()
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.done = self.vault_path / 'Done'
        
        # Ensure folders exist
        for folder in [self.pending_approval, self.approved, self.done]:
            folder.mkdir(parents=True, exist_ok=True)
        
        # Initialize client
        self.client = TwitterClient()
    
    def create_tweet_request(
        self,
        text: str,
        media_url: Optional[str] = None,
        is_thread: bool = False,
        thread_tweets: Optional[List[str]] = None,
    ) -> Path:
        """
        Create a tweet request file in Pending_Approval folder.
        
        Args:
            text: Tweet content
            media_url: URL to media
            is_thread: Whether this is a thread
            thread_tweets: List of tweets for thread
            
        Returns:
            Path to created file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'TWEET_{"THREAD" if is_thread else "SINGLE"}_{timestamp}.md'
        filepath = self.pending_approval / filename
        
        if is_thread and thread_tweets:
            content_text = '\n\n'.join([f'{i+1}. {t}' for i, t in enumerate(thread_tweets)])
        else:
            content_text = text
        
        content = f'''---
type: twitter_post_request
platform: Twitter
created: {datetime.now().isoformat()}
status: pending_approval
requires_approval: true
is_thread: {str(is_thread).lower()}
---

# Twitter Post Request

## Type
{"🧵 Thread" if is_thread else "📝 Single Tweet"}

## Content
{content_text}

{f'**Media**: {media_url}' if media_url else ''}

## To Approve
1. Review the content above
2. Move this file to `/Approved` folder to publish
3. Move to `/Rejected` to cancel

## To Execute (after approval)
```bash
python scripts/twitter_poster.py --vault {self.vault_path} --execute --file "{filepath.name}"
```

---
*Generated by Twitter Poster | AI Employee v0.3 (Gold Tier)*
'''
        
        filepath.write_text(content, encoding='utf-8')
        logger.info(f'Created tweet request: {filepath.name}')
        
        return filepath
    
    def execute_post(self, filepath: Path) -> Dict[str, Any]:
        """
        Execute an approved tweet.
        
        Args:
            filepath: Path to approved tweet file
            
        Returns:
            Result dictionary
        """
        # Read the approved file
        content = filepath.read_text(encoding='utf-8')
        
        # Parse frontmatter and content
        try:
            # Split frontmatter and body
            if content.startswith('---'):
                parts = content.split('---', 2)
                frontmatter = parts[1].strip()
                body = parts[2].strip() if len(parts) > 2 else ''
                
                # Parse YAML-like frontmatter
                metadata = {}
                for line in frontmatter.split('\n'):
                    if ':' in line:
                        key, value = line.split(':', 1)
                        metadata[key.strip()] = value.strip()
            else:
                metadata = {}
                body = content
            
            is_thread = metadata.get('is_thread', 'false').lower() == 'true'
            
            # Extract tweet content from body
            lines = body.split('\n')
            content_lines = []
            media_url = None
            in_content = False
            
            for line in lines:
                if line.startswith('## Content'):
                    in_content = True
                    continue
                elif line.startswith('##'):
                    in_content = False
                elif in_content:
                    if line.startswith('**Media**'):
                        media_url = line.split(': ')[1] if ': ' in line else None
                    elif line.strip() and not line.startswith('-') and not line.startswith('```'):
                        # Skip numbered thread markers for parsing
                        text = line.strip()
                        if text and not text.startswith('🧵') and not text.startswith('📝'):
                            content_lines.append(text)
            
            # Parse thread tweets or single tweet
            if is_thread:
                # Extract numbered tweets
                thread_tweets = []
                current_tweet = []
                
                for line in content_lines:
                    if line.startswith(tuple(f'{i}.' for i in range(1, 20))):
                        if current_tweet:
                            thread_tweets.append(' '.join(current_tweet))
                        current_tweet = [line.split('. ', 1)[1] if '. ' in line else line]
                    else:
                        current_tweet.append(line)
                
                if current_tweet:
                    thread_tweets.append(' '.join(current_tweet))
                
                if not thread_tweets:
                    thread_tweets = [' '.join(content_lines)]
                
                result = self.client.create_thread(tweets=thread_tweets)
            else:
                message = '\n'.join(content_lines).strip()
                result = self.client.create_tweet(text=message, media_url=media_url)
            
        except Exception as e:
            logger.error(f'Failed to parse tweet file: {e}')
            return {'success': False, 'error': str(e)}
        
        # Create completion record
        self._create_done_record(filepath, result)
        
        # Move file to Done
        done_path = self.done / filepath.name
        filepath.rename(done_path)
        
        return {
            'success': True,
            'result': result,
            'done_file': str(done_path),
        }
    
    def _create_done_record(self, original_path: Path, result: Dict[str, Any]):
        """Create a record in Done folder."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'TWEET_COMPLETED_{timestamp}.md'
        filepath = self.done / filename
        
        content = f'''---
type: twitter_post_completed
completed: {datetime.now().isoformat()}
original_file: {original_path.name}
---

# Twitter Post - Completed

## Original Request
{original_path.read_text(encoding='utf-8')}

## Result
```json
{json.dumps(result, indent=2)}
```

## Posted At
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---
*Generated by Twitter Poster | AI Employee v0.3 (Gold Tier)*
'''
        
        filepath.write_text(content, encoding='utf-8')
    
    def post_direct(
        self,
        text: str,
        media_url: Optional[str] = None,
        is_thread: bool = False,
        thread_tweets: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Post directly without approval workflow.
        
        Args:
            text: Tweet content
            media_url: URL to media
            is_thread: Whether this is a thread
            thread_tweets: List of tweets for thread
            
        Returns:
            Result dictionary
        """
        try:
            if is_thread and thread_tweets:
                result = self.client.create_thread(tweets=thread_tweets)
            else:
                result = self.client.create_tweet(text=text, media_url=media_url)
            
        except Exception as e:
            logger.error(f'Failed to post: {e}')
            return {'success': False, 'error': str(e)}
        
        return {
            'success': True,
            'result': result,
        }


def parse_args():
    parser = argparse.ArgumentParser(description='Twitter Poster')
    parser.add_argument('--vault', required=True, help='Path to Obsidian vault')
    parser.add_argument('--text', help='Tweet text')
    parser.add_argument('--media-url', help='URL to media')
    parser.add_argument('--thread', nargs='+', help='Thread tweets (multiple)')
    parser.add_argument('--request', action='store_true', help='Create approval request')
    parser.add_argument('--execute', action='store_true', help='Execute approved tweet')
    parser.add_argument('--file', help='Path to approved tweet file')
    parser.add_argument('--direct', action='store_true', help='Post directly (no approval)')
    return parser.parse_args()


def main():
    args = parse_args()
    
    poster = TwitterPoster(vault_path=args.vault)
    
    # Execute approved tweet
    if args.execute and args.file:
        filepath = Path(args.file)
        if not filepath.is_absolute():
            # Look in Approved folder
            filepath = poster.approved / args.file
        
        if filepath.exists():
            result = poster.execute_post(filepath)
            print(json.dumps(result, indent=2))
            return 0 if result.get('success') else 1
        else:
            print(f'File not found: {filepath}')
            return 1
    
    # Create approval request
    if args.request:
        if args.thread:
            filepath = poster.create_tweet_request(
                text=args.text or '',
                is_thread=True,
                thread_tweets=args.thread,
            )
        else:
            filepath = poster.create_tweet_request(
                text=args.text or '',
                media_url=args.media_url,
            )
        print(f'Created approval request: {filepath}')
        return 0
    
    # Direct post (no approval)
    if args.direct:
        if args.thread:
            result = poster.post_direct(
                text=args.text or '',
                is_thread=True,
                thread_tweets=args.thread,
            )
        else:
            result = poster.post_direct(
                text=args.text or '',
                media_url=args.media_url,
            )
        print(json.dumps(result, indent=2))
        return 0 if result.get('success') else 1
    
    # Default: show usage
    print('Twitter Poster')
    print('=' * 50)
    print('\nUsage:')
    print('1. Create approval request (single tweet):')
    print('   python twitter_poster.py --vault PATH --request --text "Hello Twitter!"')
    print('\n2. Create approval request (thread):')
    print('   python twitter_poster.py --vault PATH --request --thread "Tweet 1" "Tweet 2" "Tweet 3"')
    print('\n3. Execute approved tweet:')
    print('   python twitter_poster.py --vault PATH --execute --file TWEET_*.md')
    print('\n4. Direct post (no approval):')
    print('   python twitter_poster.py --vault PATH --direct --text "Hello World!"')
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
